### ISSUE TITLE
help，I'm having a problem reproducing your code

### ISSUE THREAD

**Issue by bishu123456** [MexicanLemonade/LLM-Misinfo-QA#1]
Hey, I'm interested in your paper code, but I'm in the introductory stage and I'm having a problem reproducing your code, and I can understand that in the first stage of generating indexes -- model_file needs to run the model trained train_dense_encoder.py in DPR, and if so, then train dpr what is the training dataset for the dpr and the two data files you gave in the codebase CovidNews.tsv, NQ-1500.tsv should be passed in --psg_path？

**Comment by MexicanLemonade** [comment]
Hi there, I think they should be in --psg_path. I used pretrained checkpoints(encoder) and if you need to train stuff please refer to the DPR repo. I'm working on a minimal example right now to showcase the functionalities which should help clarify things, should be coming soon. If you have any more problems let me know.

**Comment by bishu123456** [comment]
Thank you very much for replying to my question, but I have a lot of difficulties training my DPR on my own, especially with the corresponding hardware environment. I'm really hard to solve, can you please upload the model_file directly, which is what you called pretrained checkpoints(encoder). Or ask you to pick it up, if you are offended, please forgive me
