### ISSUE TITLE
New question

### ISSUE THREAD

**Issue by bishu123456** [MexicanLemonade/LLM-Misinfo-QA#2]
Thank you very much for replying to my question, but I have a lot of difficulties training my DPR on my own, especially with the corresponding hardware environment. I'm really hard to solve, can you please upload the model_file directly? Which is what you called pretrained checkpoints(encoder). Or ask you to pick it up, if you are offended, please forgive me.

**Comment by bishu123456** [comment]
> Thank you very much for replying to my question, but I have a lot of difficulties training my DPR on my own, especially with the corresponding hardware environment. I'm really hard to solve, can you please upload the model_file directly, which is what you called pretrained checkpoints(encoder). Or ask you to pick it up, if you are offended, please forgive me.

**Comment by MexicanLemonade** [comment]
you can try to download DPR'd checkpoints based on their instructions: https://github.com/facebookresearch/DPR#resources--data-formats

**Comment by bishu123456** [comment]
I'm so stupid, can you tell me which checkpoint exactly to download。
![5T4G0 }LXY_@O 9FASVAY3B](https://github.com/MexicanLemonade/LLM-Misinfo-QA/assets/42245413/7811f1bc-a4d7-48aa-b315-0b307149c753)
![SYO@VI${F5R(E(`BMO%49_T](https://github.com/MexicanLemonade/LLM-Misinfo-QA/assets/42245413/4dfcb863-b670-476c-bc86-b5bb13345660)
![1Y(AL 0Y$L~AHK%I{Y9%3LK](https://github.com/MexicanLemonade/LLM-Misinfo-QA/assets/42245413/8a07b8b0-c713-4b1d-a35e-e6ca8c6bad87)

**Comment by MexicanLemonade** [comment]
Hi, we used the multiset-bert-base-encoder.
